Resources:
  # ---------------------------------------------------------------------------
  # Domain on api
  # ---------------------------------------------------------------------------

  ApiDomainName:
    Type: AWS::ApiGatewayV2::DomainName
    Properties:
      DomainName: ${self:custom.naming.use.domainNameApi}
      DomainNameConfigurations:
        - EndpointType: REGIONAL
          CertificateArn: ${self:custom.naming.use.domainNameCertArn}
          # CertificateName: customer
      # MutualTlsAuthentication:
      #   MutualTlsAuthentication
      # Tags: Json

  ApiMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties:
      ApiId: !Ref HttpApi
      # ApiMappingKey: String
      DomainName: !Ref ApiDomainName
      Stage: !Ref HttpApiStage
