#############################################################################
## Group: Database
#### Use: Database for microservice
####      - Table for kurteyts
#############################################################################

Resources:
  KurteytTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
      BillingMode: PAY_PER_REQUEST # default is PROVISIONED
      # GlobalSecondaryIndexes:
      #   - GlobalSecondaryIndex
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
      # LocalSecondaryIndexes:
      #   - LocalSecondaryIndex
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      # ProvisionedThroughput:
      #   ReadCapacityUnits: 1
      #   WriteCapacityUnits: 1
      # SSESpecification:
      #   SSESpecification
      # StreamSpecification:
      #   StreamViewType: NEW_IMAGE # NEW_AND_OLD_IMAGES
      TableName: ${param:tableNameKurteyt}
      # Tags:
      #   - Tag
      TimeToLiveSpecification:
        AttributeName: TTL
        Enabled: True

  # StreamIntegration:
  #   Type: AWS::Lambda::EventSourceMapping
  #   DependsOn: !Ref StreamLambdaFunction
  #   Properties:
  #     BatchSize: 1
  #     # BisectBatchOnFunctionError: Boolean
  #     # DestinationConfig:
  #     #   DestinationConfig
  #     Enabled: True
  #     EventSourceArn: !GetAtt KurteytTable.StreamArn
  #     FunctionName: ${param:lambdaNameStream}
  #     # MaximumBatchingWindowInSeconds: Integer
  #     # MaximumRecordAgeInSeconds: Integer
  #     # MaximumRetryAttempts: Integer
  #     ParallelizationFactor: 1
  #     StartingPosition: LATEST
