name: dev release

on:
  push:
    branches:
      - develop
    paths-ignore:
      - "**/README.md"
      - "**/dox/**"
      - "**/admin/**"

env:
  TARGET_ENV: dev

jobs:
  runit:
    runs-on: ubuntu-latest

    steps:
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Install
        run: |
          npm install

      - name: Deploy West
        run: |
          npm run deploy
