name: prd release

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
      - "**/dox/**"
      - "**/admin/**"

env:
  TARGET_ENV: prd
  SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v3

      - name: 👀 Env
        run: |
          echo "Env: ${{ env.TARGET_ENV }}"

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.PRD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PRD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: 📥 Install dependencies
        run: |
          npm install

      - name: 🚀 Deploy east
        run: |
          npm run deploy
